[[plugins]]
repository = 'Shougo/vimproc.vim'
    [plugins.build]
    windows = 'tools\\update-dll-mingw'
    cygwin  = 'make -f make_cygwin.mak'
    mac     = 'make -f make_mac.mak'
    unix    = 'make -f make_unix.mak'

# complete
[[plugins]]
repository = 'Shougo/neocomplete.vim'
depends    = 'Shougo/context_filetype.vim'
insert     = 1
    [[plugins]]
    repository = 'Shougo/neoinclude.vim'
    depends    = 'Shougo/neocomplete.vim'

[[plugins]]
repository = 'Shougo/neosnippet.vim'
depends    = ['Shougo/neosnippet-snippets', 'Shougo/context_filetype.vim']
insert     = 1
filetypes  = 'snippet'
unite_sources = ['neosnippet', 'neosnippet/user', 'neosnippet/runtime']

# Unite
[[plugins]]
repository = 'Shougo/unite.vim'
depends    = 'Shougo/neomru.vim'
    [plugins.commands]
    name     = 'Unite'
    complete = 'customlist,unite#complete_source'
    [[plugins]]
    repository = 'Shougo/neoyank.vim'
    depends    = 'Shougo/unite.vim'

[[plugins]]
repository = 'Shougo/unite-outline'

# MOTION
[[plugins]]
repository = 'rhysd/clever-f.vim'

[[plugins]]
repository = 'jiangmiao/auto-pairs'

[[plugins]]
repository = 'terryma/vim-expand-region'

# COMMENT OUT
[[plugins]]
repository = 'tyru/caw.vim'
mappings   = '<Plug>'

# SEARCH
[[plugins]]
repository = 'thinca/vim-visualstar'
mappings = [['x', '*'], ['x' , '#'], ['x', 'g*'], ['x', 'g#']]

[[plugins]]
repository = 'haya14busa/incsearch.vim'

# GIT
[[plugins]]
repository = 'tpope/vim-fugitive'

[[plugins]]
repository = 'airblade/vim-gitgutter'

[[plugins]]
repository = 'jreybert/vimagit'

[[plugins]]
repository = 'rhysd/committia.vim'

[[plugins]]
repository = 'AndrewRadev/gapply.vim'

# SYNTAX CHECK
[[plugins]]
repository = 'scrooloose/syntastic'

# STATUS LINE
[[plugins]]
repository = 'itchyny/lightline.vim'

# COLOR
[[plugins]]
repository = 'w0ng/vim-hybrid'

[[plugins]]
repository = 'fuenor/qfixhowm.git'

[[plugins]]
repository = 'osyo-manga/unite-qfixhowm'
