[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
hook_post_source = '''
let g:deoplete#enable_at_startup = 1
'''

[[plugins]]
repo = 'zchee/deoplete-clang'
on_ft = ['h', 'c', 'hpp', 'cpp', 'cc']
hook_post_source = '''
if has('unix')
    let g:deoplete#sources#clang#libclang_path = '/usr/lib/llvm-3.8/lib/libclang.so'
    let g:deoplete#sources#clang#clang_header =  '/usr/lib/clang/3.8'
endif
if has('mac')
    let g:deoplete#sources#clang#libclang_path = '/usr/local/Cellar/llvm/3.6.2/lib/libclang.dylib'
    let g:deoplete#sources#clang#clang_header = '/usr/local/Cellar/llvm/3.6.2/lib/clang'
endif
'''

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = ['python']

[[plugins]]
repo = 'osyo-manga/vim-monster'
on_ft = ['ruby']
hook_post_source = '''
let g:monster#completion#rcodetools#backend = "async_rct_complete"
let g:deoplete#sources#omni#input_patterns = {
\   "ruby" : '[^. *\t]\.\w*\|\h\w*::',
\}
'''

[[plugins]]
repo = 'Shougo/neoinclude.vim'
on_i = 1

[[plugins]]
repo = 'zchee/deoplete-go'
on_ft = 'go'
