# Markdown
[[plugins]]
repo = 'tyru/open-browser.vim'
on_ft = 'markdown'

[[plugins]]
repo = 'kannokanno/previm'
on_ft = 'markdown'

[[plugins]]
repo = 'rhysd/vim-clang-format'
on_ft = ['h', 'c', 'hpp', 'cpp', 'cc']
hook_post_source = '''
let g:clang_format#style_options = {
   \ "BasedOnStyle" : "Google",
   \ "IndentWidth" : 4,
   \ "AccessModifierOffset" : -4,
   \ "Standard" : "C++11",
   \ "ColumnLimit" : "110",
   \ "BreakConstructorInitializersBeforeComma" : "true",
   \ "ConstructorInitializerAllOnOneLineOrOnePerLine" : "false",
   \ "IndentCaseLabels" : "false",
   \ "AlwaysBreakTemplateDeclarations" : "true",
   \ "AllowShortFunctionsOnASingleLine" : "Inline",
   \ "AllowShortIfStatementsOnASingleLine" : "false",
   \ "UseTab" : "Never"}

autocmd FileType c,cpp nmap <buffer>,cf :ClangFormat<CR>
'''
