[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
let g:lightline = { 
\   'colorscheme': 'wombat'
\ }
'''

[[plugins]]
repo = 'w0ng/vim-hybrid'
hook_add = '''
function! s:color()
    set background=dark
    colorscheme hybrid
    hi Normal ctermbg=NONE

    if has('unix')
        hi LineNr ctermfg=7
        hi CursorLineNr ctermfg=7
    endif
    if has('mac')
        hi LineNr ctermfg=8
        hi CursorLineNr ctermfg=8
    endif
    hi CursorLine ctermbg=235 guibg=Grey40
    hi Search ctermfg=250 ctermbg=26
    hi Comment ctermfg=7

    hi clear SpellBad
    hi SpellBad cterm=underline
    hi clear SpellCap
    hi SpellCap cterm=underline
    hi clear SpellRare
    hi SpellRare cterm=underline
    hi clear SpellLocal
    hi SpellLocal cterm=underline

    hi MatchParen ctermfg=26 ctermbg=NONE
endfunction

augroup initColor
    autocmd!
    autocmd VimEnter * nested call s:color()
augroup END
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
hook_add = '''
let g:deoplete#enable_at_startup = 1
"let g:deoplete#disable_auto_complete = 1
'''

# Require unite-outline
[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
" Insert move cursol C-t C-g
" Insert preview C-v
" The prefix key
nnoremap [denite] <Nop>
nmap     <Space>u [denite]

nnoremap <silent> <Space>b :Denite buffer -mode=normal <CR>

nnoremap <silent> [denite]y :Denite neoyank -mode=normal <CR>
nnoremap <silent> [denite]gg :Denite grep -mode=normal <CR>
nnoremap <silent> [denite]gc :DeniteCursorWord grep -mode=normal <CR>
nnoremap <silent> [denite]ff :Denite file_rec -mode=normal <CR>
'''
hook_post_source = '''
" Change value
"call denite#custom#var('grep', 'command', ['dgrep'])
'''

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
else
    let cmd = 'make'
endif
let g:dein#plugin.build = cmd
'''

[[plugins]]
repo = 'cocopon/vaffle.vim'

[[plugins]]
repo = 'fuenor/qfixhowm'
hook_add = '''
let QFixHowm_Key = 'm'

let howm_dir          = '~/Dropbox/howm'
let howm_filename     = '%Y/%m/%Y-%m-%dT%H%M%S.txt'
let howm_fileencoding = 'utf-8'
let howm_fileformat   = 'unix'
let QFixHowm_FileType = 'markdown'
'''

[[plugins]]
repo = 'rhysd/clever-f.vim'
hook_add = '''
let g:clever_f_across_no_line=1
'''

[[plugins]]
repo = 'haya14busa/incsearch.vim'
hook_add = '''
map /  <Plug>(incsearch-forward)
map ?  <Plug>(incsearch-backward)
map g/ <Plug>(incsearch-stay)
'''

[[plugins]]
repo = 'tyru/caw.vim'
hook_add = '''
" デフォルトマッピングを OFF
let g:caw_no_default_keymappings = 1
" キーマッピング
nmap <silent> ,/ <Plug>(caw:hatpos:toggle)
vmap <silent> ,/ <Plug>(caw:hatpos:toggle)
'''

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/neoyank.vim'
hook_add = '''
let g:neoyank#limit = 50
'''

[[plugins]]
repo = 'Shougo/unite-outline'
hook_add = '''
nnoremap <silent> <Space>ul :Denite unite:outline -mode=normal <CR>
'''

[[plugins]]
repo = 'hewes/unite-gtags'
hook_add = '''
" lists references of a word. (It executes global -qrs -e <pattern> in internal.)
nnoremap <silent> <Space>gr :Denite unite:gtags/ref -mode=normal <CR>
" lists definitions of a word. (It executes global -qd -e <pattern> in internal.)
nnoremap <silent> <Space>gd :Denite unite:gtags/def -mode=normal <CR>
" lists grep result of a word. (It executes global -qg -e <pattern> in internal.)
" nnoremap <silent> <Space>gg :Denite unite:gtags/grep <CR>
'''

[[plugins]]
repo = 'Shougo/neoinclude.vim'
on_i = 1
