[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
let g:lightline = { 
\   'colorscheme': 'wombat'
\ }
'''

[[plugins]]
repo = 'w0ng/vim-hybrid'
hook_add = '''
function! s:color()
    set background=dark
    colorscheme hybrid
    hi Normal ctermbg=NONE

    if has('unix')
        hi LineNr ctermfg=7
        hi CursorLineNr ctermfg=7
    endif
    if has('mac')
        hi LineNr ctermfg=8
        hi CursorLineNr ctermfg=8
    endif
    hi CursorLine ctermbg=235 guibg=Grey40
    hi Search ctermfg=250 ctermbg=26

    hi clear SpellBad
    hi SpellBad cterm=underline
    hi clear SpellCap
    hi SpellCap cterm=underline
    hi clear SpellRare
    hi SpellRare cterm=underline
    hi clear SpellLocal
    hi SpellLocal cterm=underline

    hi MatchParen ctermbg=1
endfunction

augroup initColor
    autocmd!
    autocmd VimEnter * nested call s:color()
augroup END
'''

[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'neomru.vim'
hook_add = '''
let g:neoyank#limit = 50
let g:unite_source_file_mru_limit = 50
let g:unite_split_rule = 'botright'

nnoremap [unite]    <Nop>
nnoremap <Space>uu  :Unite -start-insert <CR>

nnoremap <silent> <Space>b :Unite buffer<CR>
nnoremap <silent> <Space>ut :<C-u>Unite tab<CR>
nnoremap <silent> <Space>uy :<C-u>Unite history/yank<CR>
nnoremap <silent> <Space>ufa :Unite -start-insert file_rec/async:!<CR>
nnoremap <silent> <Space>ufg :Unite -start-insert file_rec/git<CR>

nnoremap <silent> <Space>ug  :<C-u>Unite grep: -buffer-name=search-buffer<CR>
if executable('hw')
  let g:unite_source_grep_command = 'hw'
  let g:unite_source_grep_default_opts = '--no-group --no-color'
  let g:unite_source_grep_recursive_opt = ''
endif
'''

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
hook_add = '''
let g:deoplete#enable_at_startup = 1

inoremap <expr><C-h> deoplete#smart_close_popup()."\<C-h>"
inoremap <expr><BS>  deoplete#smart_close_popup()."\<C-h>"
inoremap <expr><C-g> deoplete#cancel_popup()."\<C-h>"

" <CR>: close popup and save indent.
inoremap <silent> <CR> <C-r>=<SID>my_cr_function()<CR>
function! s:my_cr_function() abort
  return deoplete#close_popup() . "\<CR>"
endfunction

'''

[[plugins]]
repo = 'zchee/deoplete-clang'
on_ft = ['h', 'c', 'hpp', 'cpp', 'cc']
hook_add = '''
if has('unix')
    let g:deoplete#sources#clang#libclang_path = '/usr/lib/llvm-3.5/lib/libclang.so'
    let g:deoplete#sources#clang#clang_header =  '/usr/include/llvm-3.5/llvm'
endif
if has('mac')
    let g:deoplete#sources#clang#libclang_path = '/usr/local/Cellar/llvm/3.6.2/lib/libclang.dylib'
    let g:deoplete#sources#clang#clang_header = '/usr/local/Cellar/llvm/3.6.2/lib/clang'
endif
'''

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
else
    let cmd = 'make'
endif
let g:dein#plugin.build = cmd
'''

[[plugins]]
repo = 'rhysd/clever-f.vim'
hook_add = '''
let g:clever_f_across_no_line=1
'''

[[plugins]]
repo = 'tyru/caw.vim'
hook_add = '''
" デフォルトマッピングを OFF
let g:caw_no_default_keymappings = 1
" キーマッピング
nmap <silent> ,/ <Plug>(caw:i:toggle)
vmap <silent> ,/ <Plug>(caw:i:toggle)
'''

[[plugins]]
repo = 'rhysd/committia.vim'
on_ft = ['gitcommit']
hook_add = '''
let g:committia_hooks = {}
function! g:committia_hooks.edit_open(info)
    " If no commit message, start with insert mode
    if a:info.vcs ==# 'git' && getline(1) ==# ''
        startinsert
    end

    " Scroll the diff window from insert mode
    " Map <C-n> and <C-p>
    imap <buffer><C-n> <Plug>(committia-scroll-diff-down-half)
    imap <buffer><C-p> <Plug>(committia-scroll-diff-up-half)
endfunction
'''

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add  = '''
let g:rooter_disable_map = 1
let g:rooter_change_directory_for_non_project_files = 1
let g:gitgutter_sign_column_always = 1
let g:gitgutter_sign_added = '✚'
let g:gitgutter_sign_modified = '➜'
let g:gitgutter_sign_removed = '_'
let g:gitgutter_realtime = 0
let g:gitgutter_eager = 1
let g:gitgutter_max_signs = 2000
let g:gitgutter_escape_grep = 1
'''

[[plugins]]
repo = 'Shougo/vimfiler.vim'
depends = 'Shougo/unite.vim'
hook_add = '''
"vimデフォルトのエクスプローラをvimfilerで置き換える
let g:vimfiler_as_default_explorer = 1
"Auto change of current directory
let g:vimfiler_enable_auto_cd = 1

"デフォルトのキーマッピングを変更
if !has('gui_running')
    nnoremap <silent> <Space>ff :VimFilerBufferDir -simple<CR>
else
    nnoremap <silent> <Space>ff :VimFiler<CR>
end

augroup vim-filer
    autocmd FileType vimfiler call s:vimfiler_my_settings()
augroup END
function! s:vimfiler_my_settings()
    nmap <buffer> q <Plug>(vimfiler_hide)
    nmap <buffer> Q <Plug>(vimfiler_exit)
    nmap <buffer> <C-j> <C-w>j
    nmap <buffer> <C-k> <C-w>k
    nmap <buffer> <C-h> <C-w>h
    nmap <buffer> <C-l> <C-w>l
endfunction
'''

[[plugins]]
repo = 'hewes/unite-gtags'
hook_add = '''
" lists references of a word. (It executes global -qrs -e <pattern> in internal.)
nnoremap <silent> <Space>gr :<C-u>Unite gtags/ref<CR>
" lists definitions of a word. (It executes global -qd -e <pattern> in internal.)
nnoremap <silent> <Space>gd :<C-u>Unite gtags/def<CR>
" lists grep result of a word. (It executes global -qg -e <pattern> in internal.)
" nnoremap <silent> <Space>gg :<C-u>Unite gtags/grep<CR>
'''

[[plugins]]
repo = 'Shougo/unite-outline'
hook_add = '''
nnoremap <silent> <Space>uo :<C-u>Unite -vertical -no-quit -keep-focus outline<CR>
'''

[[plugins]]
repo = 'haya14busa/incsearch.vim'
hook_add = '''
map /  <Plug>(incsearch-forward)
map ?  <Plug>(incsearch-backward)
map g/ <Plug>(incsearch-stay)
'''

[[plugins]]
repo = 'Shougo/neoyank.vim'
hook_add = '''
let g:neoyank#limit = 50
'''

[[plugins]]
repo = 'tyru/open-browser.vim'
on_ft = 'markdown'

[[plugins]]
repo = 'kannokanno/previm'
on_ft = 'markdown'

[[plugins]]
repo = 'Shougo/echodoc'
