[[plugins]]
repo = 'vim-jp/vim-cpp'
on_ft = 'cpp'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = 'markdown'
hook_add = '''
let g:vim_markdown_folding_disabled = 1
'''

[[plugins]]
repo = 'koara-local/vim-wayland'
on_ft = ['c', 'cpp']

[[plugins]]
repo = 'Townk/vim-qt'
on_ft = ['c', 'cpp']

[[plugins]]
repo = 'peterhoeg/vim-qml'
on_ft = 'qml'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
source_add = '''
set noexpandtab
set shiftwidth=8
set softtabstop=8
'''
