[colors]
foreground = "#d8dee9"
background = "#1D1F21"

cursor_bg = "#d8dee9"
cursor_fg = "#282828"
cursor_border = "#eceff4"

selection_fg = "#eceff4"
selection_bg = "#4c566a"

ansi = [
  "#3b4252",
  "#81a1c1",
  "#88c0d0",
  "#a3be8c",
  "#b48ead",
  "#bf616a",
  "#e5e9f0",
  "#ebcb8b",
]

brights = [
  "#4c566a",
  "#81a1c1",
  "#8fbcbb",
  "#a3be8c",
  "#b48ead",
  "#bf616a",
  "#eceff4",
  "#ebcb8b",
]

[colors.indexed]

[metadata]
aliases = ["zenburn"]
name = "zenburn"
# origin_url = "https://github.com/mbadolato/iTerm2-Color-Schemes"
wezterm_version = "Always"
