source $HOME/.config/zsh/zshrc-common
source $HOME/.config/zsh/zshrc-env
source $HOME/.config/zsh/zshrc-plugin
source $HOME/.config/zsh/zshrc-func
source $HOME/.config/zsh/zshrc-cheatcheet
source $HOME/.config/zsh/zshrc-alias.common

fpath+=($HOME/.config/zsh)
autoload -U compinit
compinit -u
# autoload -Uz ghq

case "${OSTYPE}" in
  darwin*)
    source $HOME/.config/zsh/zshrc-alias.mac
    ;;
  linux*)
    source $HOME/.config/zsh/zshrc-alias.linux
    ;;
esac

# zshrc local setting
[ -f $HOME/.config/zsh/zshrc.local ] && source $HOME/.config/zsh/zshrc.local
