# https://github.com/sxyazi/yazi/blob/v0.3.3/yazi-config/preset/yazi.toml

[mgr]
show_hidden = false

[opener]
play = [
  { run = 'vlc "$@"', orphan = true, desc = "VLC", for = "unix" },
  { run = 'mpv --no-video "$@"', orphan = true, desc = "MVP Audio", for = "unix" },
  { run = 'mpv "$@"', orphan = true, desc = "MVP", for = "unix" },
  { run = '''mediainfo "$1"; echo "Press enter to exit"; read _''', block = true, desc = "Show media info", for = "unix" },
]
edit = [
  { run = 'vi "$@"', block = true, for = "unix" },
  { run = "%EDITOR% %*",  block = true, for = "windows" },
  { run = 'code "$@"', block = false, desc = "VSCode", for = "unix" },
]

[[opener.set-wallpaper]]
run = '''
  osascript -e 'on run {img}' -e 'tell application "system events" to set picture of every desktop to img' -e 'end run' %s1
'''
for  = "macos"
desc = "set as wallpaper"

[[opener.set-wallpaper1]]
run = '''
  osascript -e 'on run {img}' -e 'tell application "system events" to set picture of desktop 1 to img' -e 'end run' %s1
'''
for  = "macos"
desc = "set as wallpaper1"

[[opener.set-wallpaper2]]
run = '''
  osascript -e 'on run {img}' -e 'tell application "system events" to set picture of desktop 2 to img' -e 'end run' %s1
'''
for  = "macos"
desc = "set as wallpaper2"

[[opener.open-pdf]]
run = '''
  tdf "$@"
'''
block = true
desc = "Open pdf by tdf"

[open]
prepend_rules = [
  { name = "*.mkv", use = ["play"] },
  { name = "*.m3u", use = ["play"] },
  { name = "*.gsheet", use = ["open"] },
  { name = "*.gdraw", use = ["open"] },
  { mime = "application/pdf", use = ["open-pdf", "open"] },
  { mime = "image/*", use = ["open", "set-wallpaper", "set-wallpaper1", "set-wallpaper2"] },
]
